---
- name: Copying over a package and installing to only CentOS 7 in the enviorment using condion
  hosts: myservers
  tasks:
    - name: Copying the package to the CentOS 7  managed nodes only
      copy:
        src: /tmp/httpd-2.4.6-90.el7.centos.x86_64.rpm
        dest: /tmp
        owner: root
        group: root
        mode: 0777
      when: ansible_distribution_major_version == "7"
    - name: Installing the local package to the CentOS 7  managed nodes only
      yum:
        name: /tmp/httpd-2.4.6-90.el7.centos.x86_64.rpm
        state: present
      when: ansible_distribution_major_version == "7"
    - name: starting and enabling the service 
      service:
        name: httpd
        state: started
        enabled: yes
      when: ansible_distribution_major_version == "7"
